name = "BLRemoteDataServer"
uuid = "ff10e4b9-378f-4bad-8d64-19def9d79a0d"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.1.6"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Blio = "87855aa7-8b24-49b4-b316-97c011f78d17"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
H5Zbitshuffle = "51b4e782-877f-4ccf-958a-27bf628210da"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
SeticoreCapnp = "5f96b823-c651-45d3-b54e-600e338e6562"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SwagUI = "bf05d729-34b2-4f1f-a2f1-2452bece7ebc"
SwaggerMarkdown = "1b6eb727-ad4b-44eb-9669-b9596a6e760f"

[compat]
Blio = "0.5.10"
Genie = "5.18.1"
H5Zbitshuffle = "0.1.1"
HDF5 = "0.16.15"
HTTP = "1.9.14"
SeticoreCapnp = "0.4.0"
SwagUI = "0.10.0"
SwaggerMarkdown = "0.2.1"
